### ISSUE TITLE
Remove border in clay container 

### ISSUE THREAD

**Issue by rashmisridar** [mcaubrey/clay_containers#6] opened 2020-08-11 06:48 UTC
Let me know the exact solution

Expected output 
![WhatsApp Image 2020-08-10 at 10 31 16](https://user-images.githubusercontent.com/8536749/89865823-0d3af380-dbcc-11ea-8441-c7369aeece4d.jpeg)

Output from my code design 
![WhatsApp Image 2020-08-11 at 09 20 11](https://user-images.githubusercontent.com/8536749/89865947-496e5400-dbcc-11ea-9764-60b379efd47f.jpeg)

Here my code 
https://github.com/rashmisridar/neuromorphic_design

**Comment by MichaelCharles** [comment] 2021-03-10 02:06
This has to do with the implementation of embossed widgets. As such I'm going to close it as a duplicate of #2 

I haven't decided yet whether or not I'm going to implement embossed widgets using shadows as opposed to gradients. 

What you are seeing isn't a border per se, but rather where the shadow ends and the gradient within the container starts.

**Closed as completed by MichaelCharles** 2021-03-10 02:06 UTC
